### ISSUE TITLE
Minimum System Requirements

### ISSUE THREAD

**Issue by fondlez** [warperia/warperia-frontend#1]
Hello,

As a desktop client, what are the minimum system requirements, please? I cannot see them listed anywhere either here or on the website people are redirected to download the latest release.

**Comment by warperia** [comment]
Hey!

Thank you for pointing that out. I will add minimum system requirements on our website and in the repo description. 

Warperia is built with ElectronJS, so the basic system requirements are:

- Intel Pentium 4 or later (64 bit)
- Windows 10 or later
- At least 512 MB of RAM

Chances are if your computer can run Google Chrome, then it will be able to run Warperia.
